---
name: Checks

on:
  push:
    branches: [7.x]
  pull_request:
    branches: [7.x]

jobs:
  checks:
    name: Rubocop check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install bundler and gems
        run: |
          gem install bundler
          bundle config set without packaging documentation
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop check
        run: bundle exec rake rubocop

